# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='exigencia_ramo_profesor',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='comentario',
            name='importancia_asistencia_auxiliar',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='comentario',
            name='importancia_asistencia_catedra',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='comentario',
            name='metodos_profesor',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='comentario',
            name='recomienda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='semestre',
            field=models.CharField(choices=[('P', 'Primavera'), ('O', 'Otono'), ('V', 'Verano')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='comentario',
            name='year',
            field=models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, max_length=4, verbose_name='year'),
        ),
    ]
