# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-02 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170626_1643'),
        ('core', '0006_auto_20170623_1547'),
    ]

    operations = [
    ]
