# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='vote_score',
        ),
    ]
